fix(pkg/sensors): account for `shared` maps when resolving spec maps
For bpf objects built with eg: `sleepable_offload` map,
`spec.Maps` would contain the map, but `resolveMap` would fail
to find a matching map since it only looked up for maps pinned to
the load program or user maps.

This caused issues like:
```
$ sudo ./tetra tracingpolicy add /home/fdipierr/uprobe_test/policies/uprobe.yaml
Error: failed to add tracing policy: rpc error: code = Unknown desc = sensor generic_uprobe from collection uprobe-libcliappmgr failed to load: failed prog bpf/objs/bpf_multi_uprobe_v61.o kern_version 458766 loadInstance: opening collection 'bpf/objs/bpf_multi_uprobe_v61.o' failed: using replacement map sleepable_preload: MaxEntries: 32768 changed to 1: map spec is incompatible with existing map
```

The issue was triggered when a policy that made use of a shared map
(eg: an Override action for uprobes) was loaded and then a new same-type
policy that made NO use of the shared map was loaded.
The second map, failing to resolve the already-loaded shared map reference,
would try to enforce the default `max_entries` from ebpf code, ie: 1.

Signed-off-by: Federico Di Pierro <nierro92@gmail.com>